### ISSUE TITLE
embedding和scp文件

### ISSUE THREAD

**Issue by wow33214** [funcwj/voice-filter#1]
您好，我成功完成了数据模拟部分并下载了xvector，请问如何使用下载的xvector模型生成参考音频的嵌入向量？以及{mix,ref,emb}.scp这里的三个scp文件的格式依旧是标识符和音频地址的key-value对吗，我看您的代码中在处理emb时与前面两个文件不太一样，这三个文件应该如何准备？

**Comment by funcwj** [comment]
这个定义和kaldi里面的格式是一样的，每一行是一个key value对，key是一个unique的string，value是wav或者embedding的路径

**Comment by wow33214** [comment]
谢谢您的回复，在下载了您提供的xvector文件后，我该如何根据自己的数据集生成embedding，还有在train的过程中不需要将训练好的xvector模型传入吗？

**Comment by funcwj** [comment]
用下载的模型提取xvector就行了，脚本在Kaldi里面（前提是你会使用Kaldi），训练的时候只传入特征，不传模型

**Comment by wow33214** [comment]
明白了，我去尝试下，感谢指点。
